name: EKS Setup
on:
  push:
    branches: [ "main" ]
  pull_request:
  
jobs:
  Remote-Backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
          aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'
          aws-region: us-west-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Apply
        id:   apply
        run: |
          cd EKS-Infra-State-Bucket/
          terraform init
          terraform validate
          terraform plan 
          terraform apply --auto-approve
  EKS-Setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
          aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'
          aws-region: us-west-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform EKS Apply
        id:   apply
        run: |
          cd EKS/
          terraform init
          terraform validate
          terraform plan 
          terraform apply --auto-approve
      - name: Terraform ECR Apply
        id:   apply
        run: |
          cd ECR/
          terraform init
          terraform validate
          terraform plan 
          terraform apply --auto-approve
          
